description: >
  This job renders Jinja templates at the specified paths.
# What will this job do?
# Descriptions should be short, simple, and clear.

executor: default

parameters:
  path:
    type: string
    description: "Path to template file or directory containing .j2 or .jinja files."
  outputdir:
    type: string
    description: "Local path to which render Jinja templates will be written."
  persist-workspace:
    default: false
    description: Persist files to (cci) workspace for use in subsequent jobs
    type: boolean
  workspace-path:
    default: .
    description: Path of the workspace to persist to relative to workspace-root.
    type: string
  workspace-root:
    default: .
    description: >-
      Workspace root path that is either an absolute path or a path relative to
      the working directory. Defaults to '.' (the working directory)
    type: string
steps:
  - checkout
  - run:
      name: Install deps
      command: pip3 install pyyaml jinja2
  - run:
      shell: /home/circleci/.pyenv/shims/python
      environment:
        PARAM_PATH: <<parameters.path>>
        PARAM_OUTPUTDIR: <<parameters.outputdir>>
      name: Render templates
      command: <<include(scripts/render.py)>>
  - when:
      condition: << parameters.persist-workspace >>
      steps:
        - persist_to_workspace:
            paths:
              - << parameters.workspace-path >>
            root: << parameters.workspace-root >>
