description: >
  This is a Docker executor that includes the specified version of Python.
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: 3.9
    description: >
      Pick a specific cimg/python image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
